setwd("C:/Users/psingh2424/Desktop/R")
my_data <- read.csv("household_power_consumption.csv")
my_dataDateTime <- as.POSIXct(paste(my_data$Date, my_data$Time), format="%d/%m/%Y %H:%M:%S")

plot(my_dataDateTime, my_data$Sub_metering_1, type="l", ylab = "Energy sub metering", xlab = "")
points(my_dataDateTime, my_data$Sub_metering_2, type="l", col = "red")
points(my_dataDateTime, my_data$Sub_metering_3, type="l", col = "blue")
legend("topright", pch = 1, col = c("black", "blue", "red"), legend = c("Sub_Metering_1", "Sub_Metering_2", "Sub_Metering_3"))
       
png(filename="C:/Users/psingh2424/Desktop/R/plot3.png", width = 480, height = 480) 
plot(my_dataDateTime, my_data$Sub_metering_1, type="l", ylab = "Energy sub metering", xlab = "")
points(my_dataDateTime, my_data$Sub_metering_2, type="l", col = "red")
points(my_dataDateTime, my_data$Sub_metering_3, type="l", col = "blue")
legend("topright", pch = 1, col = c("black", "blue", "red"), legend = c("Sub_Metering_1", "Sub_Metering_2", "Sub_Metering_3"))
dev.off()